// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNQZXIb2qmvG9auVZ5FtGCVf3mZSaQdaM',
    appId: '1:896252077388:android:fea64d114644b9b8c59be9',
    messagingSenderId: '896252077388',
    projectId: 'ottapp-e8b34',
    databaseURL: 'https://ottapp-e8b34-default-rtdb.firebaseio.com',
    storageBucket: 'ottapp-e8b34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAp5A-TBzjBNxUSXrAAYqOxkQUl8SJ-7U',
    appId: '1:896252077388:ios:32c26751e7c48f92c59be9',
    messagingSenderId: '896252077388',
    projectId: 'ottapp-e8b34',
    databaseURL: 'https://ottapp-e8b34-default-rtdb.firebaseio.com',
    storageBucket: 'ottapp-e8b34.firebasestorage.app',
    iosBundleId: 'com.tr3bolplus2026',
  );

}